### ISSUE TITLE
Error with log: false

### ISSUE THREAD

**Issue by prtngn** [zookzook/elixir-mongodb-driver#208]
In config:
```
config :mongodb_driver,
  log: false,
  migration: [
    collection: :m,
    otp_app: :backend,
    path: "migrations",
    topology: :mongo
  ]
```

Get some more logs:
```
[backend] [2023-09-14 18:25:39] 18:25:39.818 [error] an exception was raised logging %DBConnection.LogEntry{call: :execute, query: %Mongo.Query{action: {:exec_hello, []}}, params: [], result: {:ok, %Mongo.Query{action: {:exec_hello, []}}, {%{"$clusterTime" => %{"clusterTime" => #BSON.Timestamp<1694715934:2>, "signature" => %{"hash" => #BSON.Binary<1dddf50e397da5ff6ceee500a4c868b542d92947>, "keyId" => 7243713445671993345}}, "connectionId" => 11877082, "electionId" => #BSON.ObjectId<7fffffff0000000000000006>, "hosts" => ["db-mongodb-ams3-xxx-xxx.mongo.xxx.com:27017"], "isWritablePrimary" => true, "lastWrite" => %{"lastWriteDate" => ~U[2023-09-14 18:25:34.000Z], "majorityOpTime" => %{"t" => 6, "ts" => #BSON.Timestamp<1694715934:2>}, "majorityWriteDate" => ~U[2023-09-14 18:25:34.000Z], "opTime" => %{"t" => 6, "ts" => #BSON.Timestamp<1694715934:2>}}, "localTime" => ~U[2023-09-14 18:25:39.815Z], "logicalSessionTimeoutMinutes" => 30, "maxBsonObjectSize" => 16777216, "maxMessageSizeBytes" => 48000000, "maxWireVersion" => 17, "maxWriteBatchSize" => 100000, "me" => "db-mongodb-ams3-xxx-xxx.mongo.xxx.com:27017", "minWireVersion" => 0, "ok" => 1.0, "operationTime" => #BSON.Timestamp<1694715934:2>, "primary" => "db-mongodb-ams3-xxx-xxx.mongo.xxx.com:27017", "readOnly" => false, "secondary" => false, "setName" => "db-mongodb-ams3-20859", "setVersion" => 38, "topologyVersion" => %{"counter" => 6, "processId" => #BSON.ObjectId<64a17535b27d23fa5fa85a4e>}}, %Mongo.Events.CommandStartedEvent{command: :hello, database_name: "admin", command_name: :hello, request_id: 0, operation_id: nil, connection_id: #PID<0.889.0>}, 0, 1799}}, pool_time: 41288, connection_time: 1823009, decode_time: 2617, idle_time: 134846}: ** (BadFunctionError) expected a function, got: :warning
[backend] [2023-09-14 18:25:39]     (db_connection 2.5.0) lib/db_connection.ex:1600: DBConnection.log/2
[backend] [2023-09-14 18:25:39]     (db_connection 2.5.0) lib/db_connection.ex:1578: DBConnection.log/5
[backend] [2023-09-14 18:25:39]     (mongodb_driver 1.2.0) lib/mongo.ex:1526: Mongo.exec_hello/2
[backend] [2023-09-14 18:25:39]     (stdlib 4.3) timer.erl:235: :timer.tc/1
[backend] [2023-09-14 18:25:39]     (mongodb_driver 1.2.0) lib/mongo/streaming_hello_monitor.ex:142: Mongo.StreamingHelloMonitor.get_server_description/1
[backend] [2023-09-14 18:25:39]     (mongodb_driver 1.2.0) lib/mongo/streaming_hello_monitor.ex:109: Mongo.StreamingHelloMonitor.update_server_description/1
[backend] [2023-09-14 18:25:39]     (mongodb_driver 1.2.0) lib/mongo/streaming_hello_monitor.ex:92: Mongo.StreamingHelloMonitor.handle_info/2
[backend] [2023-09-14 18:25:39]     (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
[backend] [2023-09-14 18:25:39] 
```

How i can fix it? With log: true i did't get this is errors.

**Comment by zookzook** [comment]
Which Elixir version do you use?

**Comment by prtngn** [comment]
> Which Elixir version do you use?

Elixir 1.14.4
OTP 25.3

**Comment by zookzook** [comment]
Thank you. Could you try Elixir 1.15? I updated db_connection to 2.5, maybe it is not backward compatible?

**Comment by prtngn** [comment]
I resolve this error.
Problem has been in Repo config, line `log: :warning`

```
config :backend, Backend.Repo,
  idle_interval: 10_000,
  pool_size: 40,
  queue_target: 15_000,
  timeout: 60_000,
  log: :warning
```
