### ISSUE TITLE
Error when trying to run `watch_collection`

### ISSUE THREAD

**Issue by edwinallenz** [zookzook/elixir-mongodb-driver#45]
I'm trying to test the `watch_collection` function.
After successfully connected to my replica set with and running some queries.
I ran 

`cursor =  Mongo.watch_collection(conn, "myColl", [], fn doc -> IO.puts "New Token #{inspect doc}" end, max_time: 2_000 )`

but when I ran
`cursor |> Enum.each(fn doc -> IO.puts inspect doc end)`

I got a message like this
`** (Mongo.Error) Majority read concern requested, but it is not supported by the storage engine. 148
    (mongodb_driver) lib/mongo/cursor.ex:94: anonymous fn/2 in Enumerable.Mongo.Cursor.next_fun/1
    (elixir) lib/stream.ex:1407: Stream.do_resource/5
    (elixir) lib/enum.ex:3023: Enum.each/2
`

Any guide here, what could be happening

**Comment by edwinallenz** [comment]
Found that is related to my mongo instance. Clossing the issue
